# type: ignore
# ruff: noqa
"""initial

Revision ID: 808d18e27e2f
Revises: 
Create Date: 2026-01-17 08:35:37.859598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '808d18e27e2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('speaker_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_public_id'), 'speaker', ['public_id'], unique=True)
    op.create_index(op.f('ix_speaker_speaker_id'), 'speaker', ['speaker_id'], unique=True)
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('audio_format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_public_id'), 'voice', ['public_id'], unique=True)
    op.create_index(op.f('ix_voice_speaker_id'), 'voice', ['speaker_id'], unique=False)
    op.create_table('voice_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('audio_format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sample_public_id'), 'voice_sample', ['public_id'], unique=True)
    op.create_index(op.f('ix_voice_sample_speaker_id'), 'voice_sample', ['speaker_id'], unique=False)
    op.create_table('passphrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('voice_sample_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.ForeignKeyConstraint(['voice_sample_id'], ['voice_sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passphrase_public_id'), 'passphrase', ['public_id'], unique=True)
    op.create_index(op.f('ix_passphrase_speaker_id'), 'passphrase', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_passphrase_voice_sample_id'), 'passphrase', ['voice_sample_id'], unique=False)
    op.create_table('voiceprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('voice_sample_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.ForeignKeyConstraint(['voice_sample_id'], ['voice_sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voiceprint_public_id'), 'voiceprint', ['public_id'], unique=True)
    op.create_index(op.f('ix_voiceprint_speaker_id'), 'voiceprint', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_voiceprint_voice_sample_id'), 'voiceprint', ['voice_sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voiceprint_voice_sample_id'), table_name='voiceprint')
    op.drop_index(op.f('ix_voiceprint_speaker_id'), table_name='voiceprint')
    op.drop_index(op.f('ix_voiceprint_public_id'), table_name='voiceprint')
    op.drop_table('voiceprint')
    op.drop_index(op.f('ix_passphrase_voice_sample_id'), table_name='passphrase')
    op.drop_index(op.f('ix_passphrase_speaker_id'), table_name='passphrase')
    op.drop_index(op.f('ix_passphrase_public_id'), table_name='passphrase')
    op.drop_table('passphrase')
    op.drop_index(op.f('ix_voice_sample_speaker_id'), table_name='voice_sample')
    op.drop_index(op.f('ix_voice_sample_public_id'), table_name='voice_sample')
    op.drop_table('voice_sample')
    op.drop_index(op.f('ix_voice_speaker_id'), table_name='voice')
    op.drop_index(op.f('ix_voice_public_id'), table_name='voice')
    op.drop_table('voice')
    op.drop_index(op.f('ix_speaker_speaker_id'), table_name='speaker')
    op.drop_index(op.f('ix_speaker_public_id'), table_name='speaker')
    op.drop_table('speaker')
    # ### end Alembic commands ###
