# type: ignore
# ruff: noqa
"""initial

Revision ID: db58b2e5d823
Revises:
Create Date: 2026-02-01 06:49:09.718002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "db58b2e5d823"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speaker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "public_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "speaker_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "speaker_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_speaker_public_id"), "speaker", ["public_id"], unique=True)
    op.create_index(
        op.f("ix_speaker_speaker_id"), "speaker", ["speaker_id"], unique=True
    )
    op.create_table(
        "voiceprint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "public_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("speaker_id", sa.Integer(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speaker.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voiceprint_public_id"), "voiceprint", ["public_id"], unique=True
    )
    op.create_index(
        op.f("ix_voiceprint_speaker_id"), "voiceprint", ["speaker_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voiceprint_speaker_id"), table_name="voiceprint")
    op.drop_index(op.f("ix_voiceprint_public_id"), table_name="voiceprint")
    op.drop_table("voiceprint")
    op.drop_index(op.f("ix_speaker_speaker_id"), table_name="speaker")
    op.drop_index(op.f("ix_speaker_public_id"), table_name="speaker")
    op.drop_table("speaker")
    # ### end Alembic commands ###
