# type: ignore
# ruff: noqa
"""empty message

Revision ID: 634b4cbdd0cf
Revises: 
Create Date: 2026-01-12 02:16:43.785967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '634b4cbdd0cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('speaker_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_speaker_id'), 'speaker', ['speaker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_speaker_id'), table_name='speaker')
    op.drop_table('speaker')
    # ### end Alembic commands ###
